//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CriadoParaVoceEntities17 : DbContext
    {
        public CriadoParaVoceEntities17()
            : base("name=CriadoParaVoceEntities17")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<tbArte> tbArte { get; set; }
        public virtual DbSet<tbCargo> tbCargo { get; set; }
        public virtual DbSet<tbCategoria> tbCategoria { get; set; }
        public virtual DbSet<tbCliente> tbCliente { get; set; }
        public virtual DbSet<tbContatoCliente> tbContatoCliente { get; set; }
        public virtual DbSet<tbContatoFuncionario> tbContatoFuncionario { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamento { get; set; }
        public virtual DbSet<tbFALE_CONOSCO> tbFALE_CONOSCO { get; set; }
        public virtual DbSet<tbFormaDeVenda> tbFormaDeVenda { get; set; }
        public virtual DbSet<tbFormasDePagamento> tbFormasDePagamento { get; set; }
        public virtual DbSet<tbFornecedor> tbFornecedor { get; set; }
        public virtual DbSet<tbFuncionario> tbFuncionario { get; set; }
        public virtual DbSet<tbItem_Venda> tbItem_Venda { get; set; }
        public virtual DbSet<tbNivelAcesso> tbNivelAcesso { get; set; }
        public virtual DbSet<tbPedido> tbPedido { get; set; }
        public virtual DbSet<tbProduto> tbProduto { get; set; }
        public virtual DbSet<tbProdutoFinal> tbProdutoFinal { get; set; }
        public virtual DbSet<tbTipoContato> tbTipoContato { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbVenda> tbVenda { get; set; }
        public virtual DbSet<tbVendedor> tbVendedor { get; set; }
        public virtual DbSet<USUARIOWEB> USUARIOWEB { get; set; }
        public virtual DbSet<tbParametrosPagamento> tbParametrosPagamento { get; set; }
    }
}
