//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbArte()
        {
            this.tbItem_Venda = new HashSet<tbItem_Venda>();
            this.tbProdutoFinal = new HashSet<tbProdutoFinal>();
        }
    
        public int IdArte { get; set; }
        public string NomeArte { get; set; }
        public string arquivoArte { get; set; }
        public Nullable<decimal> PrecoArte { get; set; }
        public Nullable<int> Altura { get; set; }
        public Nullable<int> Largura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItem_Venda> tbItem_Venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProdutoFinal> tbProdutoFinal { get; set; }
    }
}
