//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContatoFuncionario
    {
        public int IdContato { get; set; }
        public string ConteudoContato { get; set; }
        public Nullable<bool> StatusContato { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public Nullable<int> CodigoTipoContato { get; set; }
    
        public virtual tbFuncionario tbFuncionario { get; set; }
        public virtual tbTipoContato tbTipoContato { get; set; }
    }
}
