//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamento
    {
        public int CodigoDepartamento { get; set; }
        public string NomeDepartamento { get; set; }
        public string DescricaoDepartamento { get; set; }
        public Nullable<int> StatusDepartamento { get; set; }
    }
}
