//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbFALE_CONOSCO
    {
        public int IDMSG { get; set; }

        [Required(ErrorMessage = "Informe o seu email")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido...")]
        public string EMAIL { get; set; }

        [Required(ErrorMessage = "O nome do usuário é obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Nome do Usuário")]

        public string NOME { get; set; }
        public string Assunto { get; set; }
        public string TELEFONE { get; set; }
        public string MSG { get; set; }
        public System.DateTime DATA_MSG { get; set; }
        public Nullable<bool> STATUS_MSG { get; set; }
        public Nullable<int> CodigoUsuario { get; set; }
        public Nullable<System.DateTime> DATA_RESP_MSG { get; set; }
        public string RESP_MSG { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
