//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFormaDeVenda
    {
        public int CodigoFormaVenda { get; set; }
        public Nullable<int> CodigoPagamento { get; set; }
        public Nullable<int> CodigoVenda { get; set; }
    
        public virtual tbFormasDePagamento tbFormasDePagamento { get; set; }
        public virtual tbVenda tbVenda { get; set; }
    }
}
