//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFuncionario()
        {
            this.tbContatoFuncionario = new HashSet<tbContatoFuncionario>();
            this.tbUsuario = new HashSet<tbUsuario>();
            this.tbVendedor = new HashSet<tbVendedor>();
            this.tbVenda = new HashSet<tbVenda>();
        }
    
        public int CodigoFunc { get; set; }
        public string NomeFuncionario { get; set; }
        public string Sexo { get; set; }
        public string EmailFuncionario { get; set; }
        public string CpfFuncionario { get; set; }
        public Nullable<System.DateTime> NascimentoFuncionario { get; set; }
        public Nullable<int> StatusFuncionario { get; set; }
        public string FotoFuncionario { get; set; }
        public string NomeFoto { get; set; }
        public string Logradouro { get; set; }
        public string CEP { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public Nullable<int> CodigoDepartamento { get; set; }
        public Nullable<int> CodigoCargo { get; set; }
    
        public virtual tbCargo tbCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbContatoFuncionario> tbContatoFuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuario> tbUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVendedor> tbVendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVenda> tbVenda { get; set; }
    }
}
