//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbItem_Venda
    {
        public int CodigoItemVenda { get; set; }
        public Nullable<int> CodigoVenda { get; set; }
        public Nullable<int> CodigoProduto { get; set; }
        public Nullable<int> CodigoArte { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
    
        public virtual tbArte tbArte { get; set; }
        public virtual tbProduto tbProduto { get; set; }
        public virtual tbVenda tbVenda { get; set; }
    }
}
