//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPedido()
        {
            this.tbVenda = new HashSet<tbVenda>();
        }
    
        public int CodigoPedido { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public Nullable<int> CodigoProdutoFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVenda> tbVenda { get; set; }
        public virtual tbProdutoFinal tbProdutoFinal { get; set; }
    }
}
