//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProdutoFinal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProdutoFinal()
        {
            this.tbPedido = new HashSet<tbPedido>();
        }
    
        public int CodigoProdutoFinal { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public Nullable<int> CodigoProduto { get; set; }
        public Nullable<int> IdArte { get; set; }
        public string NomeProdutoFinal { get; set; }
        public string DescricaoProd { get; set; }
        public Nullable<bool> StatusProdutoFinal { get; set; }
        public Nullable<decimal> PrecoProdutoFinal { get; set; }
    
        public virtual tbArte tbArte { get; set; }
        public virtual tbCategoria tbCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPedido> tbPedido { get; set; }
        public virtual tbProduto tbProduto { get; set; }
    }
}
