//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuario()
        {
            this.login = new HashSet<login>();
            this.tbFALE_CONOSCO = new HashSet<tbFALE_CONOSCO>();
        }
    
        public int CodigoUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string NomeSistema { get; set; }
        public string SenhaSistema { get; set; }
        public string PinUsuario { get; set; }
        public Nullable<int> CodigoNivelAcesso { get; set; }
        public Nullable<bool> StatusUsuario { get; set; }
        public string PerguntaUsuario { get; set; }
        public string RespostaUsuario { get; set; }
        public Nullable<int> CodigoFunc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFALE_CONOSCO> tbFALE_CONOSCO { get; set; }
        public virtual tbFuncionario tbFuncionario { get; set; }
        public virtual tbNivelAcesso tbNivelAcesso { get; set; }
    }
}
