//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbVenda()
        {
            this.tbFormaDeVenda = new HashSet<tbFormaDeVenda>();
            this.tbItem_Venda = new HashSet<tbItem_Venda>();
        }
    
        public int CodigoVenda { get; set; }
        public Nullable<int> CodigoPedido { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
        public Nullable<int> CodigoFunc { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public Nullable<decimal> Troco { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFormaDeVenda> tbFormaDeVenda { get; set; }
        public virtual tbFuncionario tbFuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItem_Venda> tbItem_Venda { get; set; }
        public virtual tbPedido tbPedido { get; set; }
    }
}
