//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVendedor
    {
        public int CodigoVendedor { get; set; }
        public string NomeVendedor { get; set; }
        public Nullable<bool> StatusVendedor { get; set; }
        public Nullable<int> CodigoFunc { get; set; }
    
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}
