//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriadoParaVoceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOWEB
    {
        public int IdUsuario { get; set; }
        public string Login { get; set; }
        public string senha { get; set; }
        public string perfil { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
    }
}
